<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>Pickles</RootNamespace>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<Platform>windows</Platform>
		<Prefer32Bit>false</Prefer32Bit>
		<Configurations>
			Debug R25;Debug R26;Debug R27;
			Release R25;Release R26;Release R27
		</Configurations>
		<PackageName>Pickles</PackageName>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug R25'">
		<DynamoVersion>3.0</DynamoVersion>
		<DynamoOutput>3.0</DynamoOutput>
		<RevitVersion>2025</RevitVersion>
		<DefineConstants>$(DefineConstants);REVIT25</DefineConstants>
		<TargetFramework>net8.0-windows</TargetFramework>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release R25'">
		<DynamoVersion>3.0</DynamoVersion>
		<DynamoOutput>3.0</DynamoOutput>
		<RevitVersion>2025</RevitVersion>
		<DefineConstants>$(DefineConstants);REVIT25</DefineConstants>
		<TargetFramework>net8.0-windows</TargetFramework>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug R26'">
		<DynamoVersion>3.6</DynamoVersion>
		<DynRevitVersion>3.6</DynRevitVersion>
		<DynamoOutput>3.6</DynamoOutput>
		<RevitVersion>2026</RevitVersion>
		<DefineConstants>$(DefineConstants);REVIT26</DefineConstants>
		<TargetFramework>net8.0-windows</TargetFramework>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release R26'">
		<DynamoVersion>3.6</DynamoVersion>
		<DynRevitVersion>3.6</DynRevitVersion>
		<DynamoOutput>3.6</DynamoOutput>
		<RevitVersion>2026</RevitVersion>
		<DefineConstants>$(DefineConstants);REVIT26</DefineConstants>
		<TargetFramework>net8.0-windows</TargetFramework>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug R27'">
		<DynamoVersion>4.0</DynamoVersion>
		<DynRevitVersion>27.0</DynRevitVersion>
		<DynamoOutput>27.0</DynamoOutput>
		<RevitVersion>2027</RevitVersion>
		<DefineConstants>$(DefineConstants);REVIT27</DefineConstants>
		<TargetFramework>net10.0-windows</TargetFramework>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release R27'">
		<DynamoVersion>4.0</DynamoVersion>
		<DynRevitVersion>27.0</DynRevitVersion>
		<DynamoOutput>27.0</DynamoOutput>
		<RevitVersion>2027</RevitVersion>
		<DefineConstants>$(DefineConstants);REVIT27</DefineConstants>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup>
		<DynVersion>$(DynamoVersion)</DynVersion>
		<RevitInstallPath>C:\Program Files\Autodesk\Revit $(RevitVersion)</RevitInstallPath>
		<DynamoRevitPath>$(RevitInstallPath)\AddIns\DynamoForRevit\Revit</DynamoRevitPath>
		<PackageVersion>26.9.$(RevitVersion)</PackageVersion>
		<AssemblyVersion>$(PackageVersion)</AssemblyVersion>
		<DynRevitVersion Condition="'$(DynRevitVersion)' == ''">$(DynamoVersion)</DynRevitVersion>
		<BuildOutput>$(DynamoOutput)</BuildOutput>
		<PublishSingleFile>true</PublishSingleFile>
		<Copyright>MIT</Copyright>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>dynamo</PackageTags>
		<FolderPackages>$(AppData)\Dynamo\Dynamo Revit\$(BuildOutput)\packages\$(RootNamespace)\</FolderPackages>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Version>$(RevitVersion).$(PackageVersion)</Version>
		<FileVersion>$(PackageVersion)</FileVersion>
		<Description>$(PackageName) for Dynamo|Revit $(RevitVersion)</Description>
		<Title>$(PackageName) for Dynamo|Revit $(RevitVersion)</Title>
		<Product>$(PackageName) for Dynamo|Revit $(RevitVersion)</Product>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Nodes\Data\Pkl_Colour.cs~RFf9f8793.TMP" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DynamoVisualProgramming.Core" Version="$(DynVersion).*" />
		<PackageReference Include="DynamoVisualProgramming.DynamoCoreNodes" Version="$(DynVersion).*" />
		<PackageReference Include="DynamoVisualProgramming.ZeroTouchLibrary" Version="$(DynVersion).*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\PicklesUI\PicklesUI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<!-- Revit API -->
		<Reference Include="RevitAPI">
			<HintPath>$(RevitInstallPath)\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI">
			<HintPath>$(RevitInstallPath)\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<!-- DynamoRevit (Revit.Elements, RevitServices etc.) -->
		<Reference Include="RevitNodes">
			<HintPath>$(DynamoRevitPath)\RevitNodes.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitServices">
			<HintPath>$(DynamoRevitPath)\RevitServices.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="DynamoRevitDS">
			<HintPath>$(DynamoRevitPath)\DynamoRevitDS.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Target Name="CopyToDynamoPackage" AfterTargets="Build">
		<PropertyGroup>
			<DynamoBin>$(FolderPackages)bin\</DynamoBin>
		</PropertyGroup>
		
		<ItemGroup>
			<AssemblyFiles Include="$(TargetDir)$(AssemblyName).dll" />
			<AssemblyFiles Include="$(TargetDir)$(AssemblyName).xml" />
		</ItemGroup>
		
		<MakeDir Directories="$(DynamoBin)" />
		<Copy SourceFiles="@(AssemblyFiles)" DestinationFolder="$(DynamoBin)" />
	</Target>

	<Target Name="WritePkgJson" AfterTargets="Build">
		<PropertyGroup>
			<PkgJsonPath>$(FolderPackages)pkg.json</PkgJsonPath>
			<PkgJsonContent>
				{
				"name": "$(PackageName)",
				"version": "$(RevitVersion).$(PackageVersion)",
				"description": "As the spiritual successor to Crumple for Dynamo, Pickles captures all of its nodes and more. It provides over 300 general Revit utility nodes, as well as a new UI library and data pickling system. Please install package versions that end with the target Revit versions number only.",
				"group": "",
				"engine": "Dynamo",
				"engine_version": "$(DynVersion).0",
				"engine_version2": "$(DynVersion).0",
				"contents": "nodes",
				"license": "MIT",
				"dependencies": [],
				"host_dependencies":["Revit"],
				"keywords": [ "dynamo", "revit" ],
				"site_url": ""
				}
			</PkgJsonContent>
		</PropertyGroup>

		<MakeDir Directories="$(FolderPackages)" />
		<WriteLinesToFile File="$(PkgJsonPath)" Lines="$(PkgJsonContent)" Overwrite="true" Encoding="UTF-8" />
	</Target>

</Project>